version: '3'

services:
  service:
    build: ./service
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  service-network:
    driver: bridge

volumes:
  postgres-data:


